FROM node:22
WORKDIR /app
COPY *-static-server.bash staticServer types smshTypes .
RUN chmod +x *-static-server.bash
RUN ls
RUN ./build-static-server.bash
EXPOSE 5890
CMD ["bash", "run-static-server.bash"]
