FROM node:22
WORKDIR /app
COPY *-ws-server.bash ./
COPY server ./server/
COPY types ./types/
COPY smshTypes ./smshTypes/
COPY static ./static/
COPY .env ./.env/
RUN chmod +x *-ws-server.bash
RUN npm i -g typescript
RUN ./build-ws-server.bash
EXPOSE 5889
CMD ["bash", "run-ws-server.bash"]
