FROM node:22
WORKDIR /app
COPY ./scripts/*-ws-server.sh ./scripts/
COPY server ./server/
COPY types ./types/
COPY smshTypes ./smshTypes/
COPY static ./static/
COPY .env ./.env/
RUN chmod +x ./scripts/*-ws-server.sh
RUN npm i -g typescript
RUN ./scripts/build-ws-server.sh
EXPOSE 5889
CMD ["bash", "run-ws-server.bash"]
