FROM node:22
WORKDIR /app
COPY *-ws-server.bash server types smshTypes .
RUN chmod +x *-ws-server.bash
RUN npm i -g typescript
RUN ./build-ws-server.bash
EXPOSE 5889
CMD ["bash", "run-ws-server.bash"]
