services:
  ws-server:
    build:
      dockerfile: ./Dockerfile-ws-server
    ports:
      - "127.0.0.1:15889:5889"

  static-server:
    build:
      dockerfile: ./Dockerfile-static-server
    ports:
      - "127.0.0.1:15890:5890"
